version: "3.7"
services:
  grafana:
      image: 'grafana/grafana:6.5.0'
      ports:
        - 9001:3000
      volumes:
        - grafana-data:/var/lib/grafana
  prometheus:
      image: prom/prometheus:v2.14.0
      ports:
        - '9090:9090'
      command: '--config.file=/etc/prometheus/config.yml'
      volumes:
        - './config/prometheus/prometheus.yml:/etc/prometheus/config.yml'
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - mysqlvol:/var/lib/mysql
    networks:
      - mysql-compose-network
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cpa
    volumes:
      - mongodb:/data/db
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'rabbit'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guess
      RABBITMQ_DEFAULT_PASS: guess
    ports:
      - 5672:5672 # message communication port
      # - 15671:15671
      # - 5673:5673
      # - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API
      - 61613:61613
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
volumes:
  mysqlvol: {}
  mongodb: {}
  rabbitmq: {}
  grafana-data: {}
networks:
  mysql-compose-network:
    driver: bridge