--- INSERT ROLES
INSERT INTO roles(role_id,NAME) VALUES(1,'USER');
INSERT INTO roles(role_id,NAME) VALUES(2,'PROFISSIONAL');
INSERT INTO roles(role_id,NAME) VALUES(3,'RESPONSIBLE');
INSERT INTO roles(role_id,NAME) VALUES(4,'ADMIN');
