scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["10.18.6.218:7000"]
