## configurações da aplicação quando está em ambiente de desenvolvimento

server.port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpa
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/cpa?authSource=admin
jwt:
  expiration: 900000000
  secret: javeiroscpa
logging:
  level:
    org:
      hibernate:
        type: trace
aws:
  s3:
    region: us-east-1
    key: AKIAY5C6G5UAUB5QLUC6
    secret: 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
    bucket: cpausers



#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
