## configurações da aplicação quando está em ambiente de desenvolvimento
# ===============================
# = Server configurations
# ===============================
server.port: 7000
# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpa
    username: root
    password: root
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/cpa?authSource=admin
# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: grupo5bandtec@gmail.com
    password: yalrfndeyshwdodb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    protocol: smtp
    test-connection: false
# ===============================
# = Security configurations
# ===============================
jwt:
  expiration: 900000000
  secret: javeiroscpa
# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    org:
      hibernate:
        type: debug
# ===============================
# = AWS configurations
# ===============================
aws:
  s3:
    region: ${AWS_S3_REGION}
    key: ${AWS_S3_KEY}
    secret: ${AWS_S3_SECRET}
    bucket: ${AWS_S3_BUCKET}

broker:
  brokerVirtualHost:
  enabled: true
  host: localhost
  port: 61613
  username: guess
  password: guess

#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
