## configurações da aplicação quando está em ambiente de desenvolvimento
# ===============================
# = Server configurations
# ===============================
server.port: 7000
# ===============================
# = Hibernate datasource
# ===============================
spring:
  cloud:
    config:
      uri:
      - http://localhost:8888
