## configurações da aplicação quando está em ambiente de desenvolvimento

server.port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpa
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/cpa
jwt:
  expiration: 900000000
  secret: javeiroscpa
logging:
  level:
    org:
      hibernate:
        type: trace



#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
